// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gppkebukuvpkwqplldnj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcGtlYnVrdXZwa3dxcGxsZG5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwOTA2MTUsImV4cCI6MjA1NjY2NjYxNX0.fNsg1W9JSztGShYwCbT4QlXiHxSB0giJ85ju4X-3i7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);